name: BedWarsDuos
api: 3.x.x
version: 1.0.2
main: vixikhd\BedWars\BedWars
author: DctxDev & ShadowBonnie
description: a advance version of bedwars duos by dctxdev and shadowbonnie
Update 1.0-Dev : Fixed team bugs
Update 1.0-Official : Fixed a coupld weird bugs and added more bugs
Update 1.0-Ad : Added more bugs
Update 1.0.0-Test : Fixed bugs
Update 1.0.0-Dev : Fixed bugs
Update 1.0.0 : Added autobridge test since we added to squads plugin and sol
Update 1.0.1-Test : Fixed AutoBridge Crash
Update 1.0.1-Ad : Added more bugs
Update 1.0.2 : Fixed addxp when kill and more

permissions:
  bwd.cmd:
    description: Permission to all Bedwars commands
    default: op
    children:
      bwd.cmd.help:
        description: Permission for /bwd help
        default: op
      bwd.cmd.create:
        description: Permission for /bwd create
        default: op
      bwd.cmd.remove:
        description: Permission for /bwd remove
        default: op
      bwd.cmd.set:
        description: Permission for /bwd set
        default: op
      bwd.cmd.arenas:
        description: Permission for /bwd arenas
        default: op
      bwd.cmd.test:
        description: Permission for /bwd test
        default: op
      bwd.cmd.stoptest:
        description: Permission for /bwd stoptest
        defaut: op